
#register user  (ms auth)
POST http://localhost:8082/api/v1/auth/register
Content-Type: application/json

{
  "firstName": "nicatsa",
  "lastName": "nicat",
  "email": "nicatsa@example.com",
  "password": "Nicat123.",
  "birthDate": "29/12/2004"
}

###
#login user  (ms auth)
POST http://localhost:8082/api/v1/auth/login
Content-Type: application/json

{
  "email": "nicatsa@example.com",
  "password": "Nicat123."
}

###
# refresh token  (ms auth)
POST http://localhost:8082/api/v1/auth/refresh
Content-Type: application/json

{
  "userEmail": "nicat@example.com",
  "refreshToken": "eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJuaWNhdEBleGFtcGxlLmNvbSIsImlhdCI6MTc1OTU3NTQwNCwiZXhwIjoxNzU5NTc3MjA0fQ.RZWF6vaZ2vrPCnlUNJE0NUn4RVDOscWd_fJr2qUmwEw"
}

###
#getUserById  (ms user)
GET http://localhost:8083/api/v1/users/1

###
#getAccountByUserId  (ms account)
GET http://localhost:8084/api/v1/accounts/1

###
#creditAccount    (ms account)
POST http://localhost:8084/api/v1/accounts/1/credit
Content-Type: application/json

{
  "amount": 10000.0
}


###
#addProduct    (ms inventory)
POST http://localhost:8085/api/v1/products
Content-Type: application/json

{
  "name": "iPhone 17",
  "description": "Apple iPhone",
  "price": 2756.99,
  "stock": 8
}

###
#getProductById   (ms inventory)
GET http://localhost:8085/api/v1/products/2

###
#updateStock      (ms inventory)
PUT http://localhost:8085/api/v1/products/2/stock?quantity=5


###
#createOrder     (ms order)
POST http://localhost:8086/api/v1/orders
Content-Type: application/json
current-user-id: 1

{
  "orderItemRequests": [
    {
      "productId": 1,
      "quantity": 4
    },
    {
      "productId": 2,
      "quantity": 1
    }
  ]
}

###
# getOrderById  (ms order)
GET http://localhost:8086/api/v1/orders/11
current-user-id: 1


###
# getPaymentDetails  (ms payment)
GET http://localhost:8087/api/v1/payments/1
current-user-id: 1